[project]
name = "physics-llm-agents"
version = "0.1.0.dev0"
description = "Enhancing Physics Problem Solving in LLM Agents with Knowledge Graphs and Symbolic Math Tools"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=0.30.0",
    "beautifulsoup4>=4.14.3",
    "datasets>=4.5.0",
    "dotenv>=0.9.9",
    "httpx>=0.28.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.11",
    "langchain-openai>=1.1.9",
    "langgraph>=1.0.8",
    "llama-index>=0.14.22",
    "llama-index-tools-wikipedia>=0.5.0",
    "matplotlib>=3.10.8",
    "nltk>=3.9.2",
    "ollama>=0.6.1",
    "pgvector>=0.4.2",
    "polars>=1.38.1",
    "protobuf>=7.35.0",
    "psycopg>=3.3.2",
    "rank-bm25>=0.2.2",
    "rich>=14.3.2",
    "sentence-transformers>=5.2.2",
    "sentencepiece>=0.2.1",
    "sympy>=1.14.0",
    "transformers>=4.45.0",
    "wikipedia>=1.4.0",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.5.4",
]
