openstax:
  git_repo: https://github.com/openstax/osbooks-university-physics-bundle.git
  raw_data_path: data/raw/openstax

  extracted_xml_dir: data/extracted/openstax
  processed_txt_dir: data/processed/openstax

  parse_cfg:
    parse_topics:
      - Motion Along a Straight Line
      - Motion in Two and Three Dimensions

    skip_tags:
      - metadata

    ignore_content_tags:
      - caption
      - figure
      - iframe
      - image
      - label
      - module
      - link

    no_newline_tags:
      - sup
      - sub
      - label
      - term
      - meaning
      - emphasis
      - colspec
      - entry
      - newline
      - math
      - equation
